const books = [
    {
        id: 1,
        name: "The Lord of the Rings",
        author: "J. R. R. Tolkien",
        category: "Fantasy",
        pages: 1178,
        recommend: true,
        read: true,
    },
    {
        id: 2,
        name: "Sapiens: A Brief History of Humankind",
        author: "Yuval Noah Harari",
        category: "World History",
        pages: 464,
        recommend: true,
        read: false,
    },
    {
        id: 3,
        name: "The Way to Cook: A Cookbookf the Rings",
        author: "Julia Child",
        category: "Culinary",
        pages: 528,
        recommend: true,
        read: false,
    },
    {
        id: 4,
        name: "Long Walk to Freedom: The Autobiography of Nelson Mandela",
        author: "Nelson Mandela",
        category: "Biography",
        pages: 656,
        recommend: true,
        read: false,
    },
    {
        id: 5,
        name: "The Girl on the Train",
        author: "Paula Hawkins",
        category: "Psychological Thriller",
        pages: 336,
        recommend: false,
        read: true,
    },
    {
        id: 6,
        name: "Into the Water",
        author: "Paula Hawkins",
        category: "Psychological Thriller",
        pages: 400,
        recommend: false,
        read: true,
    },
    {
        id: 7,
        name: "Sharp Objects",
        author: "Gillian Flynn",
        category: "Thriller",
        pages: 432,
        recommend: false,
        read: false,
    },
    {
        id: 8,
        name: "The Price of Salt",
        author: "Patricia Highsmith",
        category: "Lesbian Romance",
        pages: 168,
        recommend: true,
        read: true,
    },
    {
        id: 9,
        name: "Dark Places",
        author: "Gillian Flynn",
        category: "Thriller",
        pages: 368,
        recommend: true,
        read: true,
    },
    {
        id: 10,
        name: "The Girl with the Dragon Tattoo",
        author: "Stieg Larsson",
        category: "Thriller",
        pages: 672,
        recommend: false,
        read: false,
    }
]

module.exports = books;